apiVersion: v1
kind: Service
metadata:
  name: mongo-webform
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: mongo-webform