name: Trivy Security Scan

on:
  workflow_dispatch:
#on:
#  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t pr-scan-image .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@v0.31.0
      with:
        image-ref: pr-scan-image
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL,HIGH
