name: Trivy Security Scan

on:
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/*.js'
      - '**/*.py'
      - '**/*.ts'
      - '**/*.go'
      - '**/*.yaml'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t pr-scan-image .

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@v0.11.2
      with:
        image-ref: pr-scan-image
        format: table
        exit-code: 0
        ignore-unfixed: true
